# Schema for the configuration files of the Universal Gallery module.
#
unig.settings:
  type: config_object
  label: 'Universal Gallery Settings'
  mapping:
    unig:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Test'
        default_project:
          type: text
          label: 'Default Project Name'
